"""Pydantic schema package for API request and response contracts."""

from app.schemas.admin import (
    AdminOverviewResponse,
    CreateUserAndAssignPackRequest,
    CreateUserAndAssignPackResponse,
    GeneratePackRequest,
    GeneratePackResponse,
    ListPacksResponse,
    PackStickersResponse,
    StickerPackSummary,
)
from app.schemas.auth import (
    LoginRequest,
    LogoutRequest,
    RefreshRequest,
    RegisterRequest,
    RegisterResponse,
    TokenResponse,
)
from app.schemas.recovery import (
    ClaimIssueRequest,
    ClaimIssueResponse,
    ClaimPackRequest,
    ClaimPackResponse,
    LostReportResponse,
    MarkItemLostRequest,
    OwnerInboxResponse,
    OwnerItemSummary,
    RegenerateStickerResponse,
    RegisterStickerRequest,
    RegisterStickerResponse,
    RelayMessageRequest,
    RelayMessageResponse,
    ScanStickerRequest,
    ScanStickerResponse,
    StickerSummary,
    UserItemsResponse,
    UserStickersResponse,
)

__all__ = [
    "AdminOverviewResponse",
    "ClaimIssueRequest",
    "ClaimIssueResponse",
    "ClaimPackRequest",
    "ClaimPackResponse",
    "CreateUserAndAssignPackRequest",
    "CreateUserAndAssignPackResponse",
    "GeneratePackRequest",
    "GeneratePackResponse",
    "ListPacksResponse",
    "LoginRequest",
    "LogoutRequest",
    "LostReportResponse",
    "MarkItemLostRequest",
    "OwnerInboxResponse",
    "OwnerItemSummary",
    "PackStickersResponse",
    "RefreshRequest",
    "RegenerateStickerResponse",
    "RegisterRequest",
    "RegisterResponse",
    "RegisterStickerRequest",
    "RegisterStickerResponse",
    "RelayMessageRequest",
    "RelayMessageResponse",
    "ScanStickerRequest",
    "ScanStickerResponse",
    "StickerPackSummary",
    "StickerSummary",
    "TokenResponse",
    "UserItemsResponse",
    "UserStickersResponse",
]
